# -*- coding: utf-8 -*-
"""스타트업 회사 정보 크롤링.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iI-E1IswmA1eCGh50kXkXu1Lmn7_J-Tv

1. https://dejavuqa.tistory.com/109 (selenium.by 명령어)
2. https://zeuskwon-ds.tistory.com/67(unable to locate 문제 해결)
3. https://stackoverflow.com/questions/56194094/how-to-fix-this-issue-element-not-interactable-selenium-python (클릭 버튼이 안눌릴 때 자바스크립트 코드를 이용해 클릭을 누르는 법)
"""

pip install webdriver-manager

pip install selenium

import requests
import bs4
import selenium
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager
import time
import pandas as pd

#셀레니움 버전문제 해결 코드
options = webdriver.ChromeOptions()
options.add_argument('--headless')        # Head-less 설정
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
driver = webdriver.Chrome( options=options)

driver.get("https://startupspace.kr/")
#driver.page_source   #사이트에 HTML 코드를 가져옴
driver.find_element(By.XPATH ,value='//*[@id="__next"]/div/div[4]/div/div[4]/div[1]/div/div/div[1]/div/button[2]').click()
#사이트 카드 버튼을 눌러주는 코드

#사이트에서 스타트업회사 파싱
ad=driver.find_element(By.XPATH, '//*[@id="__next"]/div/div[4]/div/div[4]/div[2]/div/div/div/div/div/div[1]/div/div/div[1]/a/div[2]').text #XML로 파싱
ad

import re
#섹터 제목 파싱 - 각 섹터별 스타트업회사 갯수 파싱
ad_title=driver.find_element(By.XPATH, '//*[@id="__next"]/div/div[4]/div/div[4]/div[2]/div/div/div/div/div/div[1]/div/h3').text
ad_title=str(ad_title)
ad_title = re.findall(r'\d+', ad_title)
print(ad_title[0])

import re
#각 섹터별 제목
for i in range(1,19,1):
  ad_title_number_list=[]
  ad_title=driver.find_element(By.XPATH, '//*[@id="__next"]/div/div[4]/div/div[4]/div[2]/div/div/div/div/div/div['+str(i)+']/div/h3').text
  print(str(i))
  ad_title_numbers = re.findall(r'\d+', ad_title)
  print(ad_title,ad_title_numbers[0],i)
  ad_title_number_list+=ad_title_numbers

#이중 중첩문으로 만들 수 있을 듯
for i in range (0+1,int(numbers1)+1) :
  ad=driver.find_element(By.XPATH, '//*[@id="__next"]/div/div[4]/div/div[4]/div[2]/div/div/div/div/div/div[1]/div/div/div['+str(i)+']/a/div[2]').text
  print(ad)

"""다음 할일 : the VC에서 정보 가져오기 (투자유치금, 투자라운드, 대표이름, 주소, 속한 산업군, 주요 제품) - the VC에 없으면 혁신의 숲 참고"""

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


#The VC에서 기업 정보 가져오기
driver.get("https://thevc.kr/")
#driver.page_source   #사이트에 HTML 코드를 가져옴
#개별 기업 마다 정보 접근

#사이트 접근
time.sleep(2)
#EC.element_to_be_clickable(By.CLASS_NAME ,'box-button.main.medium.inline-block')
element=driver.find_element(By.XPATH ,value='//*[@id="layout-header-auth-control"]/a/div[2]')
driver.execute_script("arguments[0].click();", element)

#로그인 페이지로 넘어감
driver.find_element(By.XPATH ,value='//*[@id="email"]').send_keys('comcom0221@naver.com')
driver.find_element(By.XPATH ,value='//*[@id="password"]').send_keys('ruddnjs12!')
driver.find_element(By.XPATH ,value='//*[@id="__nuxt"]/div[1]/div/div/form/button').send_keys(Keys.ENTER)
time.sleep(2)
# element=driver.find_element(By.CLASS_NAME ,value='has-prefix.has-suffix')
# driver.execute_script("arguments[0].click();", element)  # 자바 스크립트 코드 사용해서 클릭을 누른다.
# driver.implicitly_wait(10)
driver.find_element(By.CLASS_NAME ,value='has-prefix.has-suffix').send_keys(ad)
driver.find_element(By.XPATH ,value='//*[@id="__nuxt"]/div[1]/header/div[2]/div[1]/div[2]/div[1]/div[1]/div/input').send_keys(Keys.ENTER)
time.sleep(2)
driver.find_element(By.XPATH ,value='//*[@id="__nuxt"]/div[1]/div/div/section[1]/div[2]/a').click()
#사이트에 들어가서 정보 스크래핑
invest_round = driver.find_element(By.XPATH ,value='//*[@id="profile-dashboard-funding"]/div[1]/div[1]/div[1]/div[2]')
invest_round.text